import { ArrowUpRight, BadgeCheck, ExternalLink, GitBranch, GraduationCap, Mail, Wrench } from "lucide-react";
import Link from "next/link";
import { SiteFooter, SiteHeader } from "@/components/site-chrome";

const strengths = ["嵌入式设备与传感器联调", "MQTT / HTTP 数据通信", "Python / OpenCV 图像处理", "Web 页面与部署实践"];

export default function AboutPage() {
  return <><SiteHeader /><main className="inner-page"><section className="site-wrap about-hero"><div><p className="section-kicker">About</p><h1>杰子</h1><p className="about-lead">物联网工程本科生。正在把设备端积累延伸到可被访问、被理解、被持续维护的 Web 空间。</p></div><div className="about-mark" aria-hidden="true">J</div></section><section className="about-band"><div className="site-wrap about-grid"><article><GraduationCap size={26} /><p className="detail-kind">Education</p><h2>南昌航空大学</h2><p>物联网工程本科在读</p></article><article><Wrench size={26} /><p className="detail-kind">Direction</p><h2>感知 · 连接 · 展示</h2><p>嵌入式、视觉和全栈 Web 的交叉实践</p></article></div></section><section className="site-wrap strengths-section"><p className="section-kicker">Working set</p><h2>目前的工具与方向</h2><div className="strengths-grid">{strengths.map((strength) => <div key={strength}><BadgeCheck size={19} />{strength}</div>)}</div></section><section className="about-next"><div className="site-wrap about-next-grid"><div><p className="section-kicker">Next step</p><h2>把每次实践<br />变成可复用的能力。</h2></div><p>我关注的不只是某个模块能否运行，也关注它如何与其他模块协作、如何被观察，以及出现异常时能否给出明确反馈。</p></div></section><section className="site-wrap about-links"><div><p className="section-kicker">Contact</p><h2>保持联系</h2></div><div className="about-link-list"><a href="https://github.com/eaea499" target="_blank" rel="noreferrer"><GitBranch size={19} /><span><strong>GitHub</strong><small>查看源码与版本记录</small></span><ExternalLink size={17} /></a><a href="mailto:eaea499@outlook.com"><Mail size={19} /><span><strong>eaea499@outlook.com</strong><small>通过邮箱联系我</small></span><ArrowUpRight size={17} /></a><Link href="/projects"><BadgeCheck size={19} /><span><strong>项目案例</strong><small>了解我的系统实践与联调过程</small></span><ArrowUpRight size={17} /></Link></div></section><section className="site-wrap page-cta"><p>这个网站本身，也是我正在完成的项目。</p><Link href="/projects">回到项目 <ArrowUpRight size={18} /></Link></section></main><SiteFooter /></>;
}
